# upf-pod-ia-L.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: upf-deployment-ia-l
spec:
  replicas: 5 # 5 Pods pour la charge
  selector:
    matchLabels:
      app: upf-ia-l
  template:
    metadata:
      labels:
        app: upf-ia-l
    spec:
      # Ligne CLÃ‰ pour appeler votre Scheduler IA
      schedulerName: ia-scheduler 
      containers:
      - name: upf-container
        image: busybox
        command: ["sh", "-c", "echo 'IA Latency Test running'; sleep 600"]
        resources:
          requests:
            cpu: "100m"
          limits:
            cpu: "200m"